name: Code Quality

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22.20.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn format --check

      - name: Run ESLint
        run: yarn lint

      - name: Type check
        run: yarn tsc --noEmit
